logging:
  config: logback-spring.xml
  level:
    com:
      mu:
        demo:
          mapper: trace
---
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.mu.common.entity
---
server:
  port: 8080
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  cache:
    ehcache:
      config: classpath:ehcache.xml
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf-8
    username: root
  mail:
    host: smtp.qq.com
    password: ksrzdkmzbqxgchcg
    port: 465
    properties:
      from: 123@@@.com
    username: 3306687363@qq.com
  rabbitmq:
    host: 127.0.0.1
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100
    password: guest
    port: 5672
    publisher-confirms: true
    publisher-returns: true
    username: guest
  redis:
    clusterNodes: 10.102.*.*:6279,10.102.*.*:6379
    commandTimeout: 5000ms
    database: 6
    expireSeconds: 120ms
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 50
        max-idle: 20
        max-wait: 3000ms
        min-idle: 2
    password: 123456
    port: 6379
    timeout: 5000ms
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  thymeleaf:
    cache: false
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/template/
    suffix: .html
